# 排除不需要检查的目录
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",    # 常见虚拟环境目录（隐藏目录）
    "venv",     # 另一个虚拟环境命名方式
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
]

# 格式化相关设置，保持与 Black 风格一致
line-length = 88
indent-width = 4

# 指定目标 Python 版本
target-version = "py312"

[lint]
# 启用部分 pycodestyle（E4、E7、E9）、Pyflakes（F），同时增加 bugbear（B）和 flake8-quotes（Q）规则
select = ["E4", "E7", "E9", "F", "B", "Q"]

# 如果您不希望行长检查导致过多提示，可选择忽略 E501
ignore = ["E501"]

# 默认允许自动修复所有启用的规则，但 bugbear（B）的规则风险较高，因此将其列入 unfixable，避免自动修改
fixable = ["ALL"]
unfixable = ["B"]

# 对于未使用的变量，允许以下划线开头表示有意忽略
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# 针对特定文件或目录进行局部忽略配置
[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

# 针对 flake8-quotes（代码前缀 "Q"）的额外设置，统一要求文档字符串使用双引号
[lint.flake8-quotes]
docstring-quotes = "double"

[format]
# 使用双引号（与 Black 一致）
quote-style = "double"
# 使用空格缩进，不使用制表符
indent-style = "space"
# 保持魔法尾随逗号的行为
skip-magic-trailing-comma = false
# 自动检测合适的行结束符
line-ending = "auto"

# Docstring 内代码示例的自动格式化（目前处于实验阶段，如不需要可保持关闭）
docstring-code-format = false
# 当 docstring 格式化启用时，动态计算代码片段的行长
docstring-code-line-length = "dynamic"